tests/sanity: use six module to test in a compatible way
Testing
  self.assertIsInstance(interface.name, str)
Fails with Python2 with an error that looks like:
  AssertionError: u'gphy' is not an instance of <type 'str'>

because a unicode string is not of type "str" in that version. With
`six`, we can test that we get a `string_types`, eventhough we get
different string types in Python2 and Python3.